version: '3.9'

services:
  security.endpoint.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      # Mount source code into /src for live coding
      - ./Security.Endpoint.Api:/src:ro
      # - /app/bin
      # - /app/obj
      - app-logs:/logs
